[build]
bin = "myapp"
cmd = "go build -o ./tmp/main.exe ./cmd/myapp"
full_bin = "./tmp/main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "testdata", "web", "frontend", "build"]
exclude_file = []
delay = 1000 # ms

[misc]
clean_on_exit = true